kind: pipeline
name: default
type: docker

steps:
- name: build
  image: plugins/docker
  settings:
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: thatsourjake/cockpit_assets_proxy